package Vista;

import javax.swing.JFrame;
import Controlador.CtrlVista;

/**
 *
 * @author barre
 */
public class AgregarAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    
    private CtrlVista controlador;
    
    public CtrlVista getControlador() {
        return controlador;
    }

    public void setControlador(CtrlVista controlador) {
        this.controlador = controlador;
    }
    
    public AgregarAdmin(CtrlVista controlador) {
        this.controlador = controlador;
        initComponents();
        setResizable(false);
        
    }
    
    public AgregarAdmin() {
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPantalla = new javax.swing.JPanel();
        pnlSuperior = new javax.swing.JPanel();
        txtBarraBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLogo = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();
        btnAdministrar = new javax.swing.JButton();
        tlbOpciones = new javax.swing.JToolBar();
        btnPerfil = new javax.swing.JButton();
        btnOfertas = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        tlbProducto = new javax.swing.JToolBar();
        btnAtras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmar = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        btnRegistrarse1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(854, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        pnlPantalla.setBackground(new java.awt.Color(255, 255, 255));
        pnlPantalla.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlPantalla.setPreferredSize(new java.awt.Dimension(1280, 720));

        pnlSuperior.setBackground(new java.awt.Color(102, 102, 255));
        pnlSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(1280, 80));

        txtBarraBusqueda.setPreferredSize(new java.awt.Dimension(520, 40));
        txtBarraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarraBusquedaActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar 2.png"))); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLogo.setText("Logo");
        btnLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogo.setMaximumSize(new java.awt.Dimension(256, 80));
        btnLogo.setPreferredSize(new java.awt.Dimension(256, 80));
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });

        btnCarrito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Carrito.png"))); // NOI18N
        btnCarrito.setText("Carrito");
        btnCarrito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarrito.setMaximumSize(new java.awt.Dimension(170, 80));
        btnCarrito.setPreferredSize(new java.awt.Dimension(170, 80));
        btnCarrito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnAdministrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Historial.png"))); // NOI18N
        btnAdministrar.setText("Administrar");
        btnAdministrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdministrar.setMaximumSize(new java.awt.Dimension(120, 60));
        btnAdministrar.setPreferredSize(new java.awt.Dimension(120, 60));
        btnAdministrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(txtBarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSuperiorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tlbOpciones.setBackground(new java.awt.Color(102, 102, 255));
        tlbOpciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tlbOpciones.setRollover(true);
        tlbOpciones.setMaximumSize(new java.awt.Dimension(1280, 60));
        tlbOpciones.setPreferredSize(new java.awt.Dimension(1280, 60));

        btnPerfil.setBackground(new java.awt.Color(102, 102, 255));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        btnPerfil.setFocusable(false);
        btnPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPerfil.setMaximumSize(new java.awt.Dimension(160, 60));
        btnPerfil.setPreferredSize(new java.awt.Dimension(85, 60));
        btnPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        tlbOpciones.add(btnPerfil);

        btnOfertas.setBackground(new java.awt.Color(102, 102, 255));
        btnOfertas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOfertas.setForeground(new java.awt.Color(255, 255, 255));
        btnOfertas.setText("Ofertas");
        btnOfertas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        btnOfertas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOfertas.setMaximumSize(new java.awt.Dimension(160, 60));
        btnOfertas.setPreferredSize(new java.awt.Dimension(85, 60));
        btnOfertas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertasActionPerformed(evt);
            }
        });
        tlbOpciones.add(btnOfertas);

        btnCategorias.setBackground(new java.awt.Color(102, 102, 255));
        btnCategorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        btnCategorias.setText("Categorias");
        btnCategorias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        btnCategorias.setFocusable(false);
        btnCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategorias.setMaximumSize(new java.awt.Dimension(160, 60));
        btnCategorias.setPreferredSize(new java.awt.Dimension(85, 60));
        btnCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        tlbOpciones.add(btnCategorias);

        tlbProducto.setBackground(new java.awt.Color(255, 255, 255));
        tlbProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tlbProducto.setRollover(true);
        tlbProducto.setMaximumSize(new java.awt.Dimension(1280, 60));
        tlbProducto.setMinimumSize(new java.awt.Dimension(1280, 60));
        tlbProducto.setPreferredSize(new java.awt.Dimension(1280, 60));

        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setFocusable(false);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAtras.setMaximumSize(new java.awt.Dimension(200, 60));
        btnAtras.setPreferredSize(new java.awt.Dimension(200, 60));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        tlbProducto.add(btnAtras);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 266));
        jPanel1.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Correo Electrónico:");
        jLabel2.setMaximumSize(new java.awt.Dimension(100000, 10000));
        jLabel2.setMinimumSize(new java.awt.Dimension(175, 24));
        jLabel2.setPreferredSize(new java.awt.Dimension(175, 24));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre de Usuario:");
        jLabel4.setMaximumSize(new java.awt.Dimension(100000, 10000));
        jLabel4.setMinimumSize(new java.awt.Dimension(175, 24));
        jLabel4.setPreferredSize(new java.awt.Dimension(175, 24));

        txtCorreo.setPreferredSize(new java.awt.Dimension(192, 24));

        txtUsuario.setPreferredSize(new java.awt.Dimension(192, 24));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Nuevo Administrador");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Confirmar Contraseña:");
        jLabel3.setMaximumSize(new java.awt.Dimension(100000, 10000));
        jLabel3.setMinimumSize(new java.awt.Dimension(175, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(175, 24));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contraseña:");
        jLabel5.setMaximumSize(new java.awt.Dimension(100000, 10000));
        jLabel5.setMinimumSize(new java.awt.Dimension(175, 24));
        jLabel5.setPreferredSize(new java.awt.Dimension(175, 24));

        txtConfirmar.setPreferredSize(new java.awt.Dimension(192, 24));

        txtContra.setPreferredSize(new java.awt.Dimension(192, 24));

        btnRegistrarse1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarse1.setText("Registrarse");
        btnRegistrarse1.setActionCommand("Agregar");
        btnRegistrarse1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarse1.setMaximumSize(new java.awt.Dimension(120, 60));
        btnRegistrarse1.setPreferredSize(new java.awt.Dimension(120, 60));
        btnRegistrarse1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarse1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnRegistrarse1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnRegistrarse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 266));
        jPanel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE)
            .addComponent(tlbOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlbProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE)
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(tlbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tlbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlPantalla, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBarraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarraBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarraBusquedaActionPerformed

    private void btnOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertasActionPerformed
        // TODO add your handling code here:
        controlador.btnOferta(this);
    }//GEN-LAST:event_btnOfertasActionPerformed

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
        controlador.btnLogo(this);
    }//GEN-LAST:event_btnLogoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        controlador.btnBuscar(txtBarraBusqueda.getText(), this);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarActionPerformed
        // TODO add your handling code here:
        controlador.btnAdministrar(this);
    }//GEN-LAST:event_btnAdministrarActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
        controlador.btnCarrito(this);
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        // TODO add your handling code here:
        controlador.btnCategoria(this);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        controlador.btnPerfil(this);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        controlador.btnAtras(this);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarse1ActionPerformed
        // TODO add your handling code here:
        String nombre = txtUsuario.getText().trim();
    String correo = txtCorreo.getText().trim();
    String contra = txtContra.getText();
    String confirmar = txtConfirmar.getText();

    if (nombre.isBlank() || correo.isBlank() || contra.isBlank() || confirmar.isBlank()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completa todos los campos.");
        return;
    }

    char[] pwd = contra.toCharArray();
    char[] pwdConfirm = confirmar.toCharArray();

    if (controlador == null || controlador.getCtrlUsuarios() == null) {
        System.out.println("Error: controlador o CtrlUsuarios es null");
        javax.swing.JOptionPane.showMessageDialog(this, "Error interno al registrar. Consulte al administrador.");
        java.util.Arrays.fill(pwd, '\0');
        java.util.Arrays.fill(pwdConfirm, '\0');
        return;
    }

    boolean exito = false;
    String correoLower = correo.toLowerCase();

    // CASO 1: correo corporativo -> registrar como ADMIN
    if (correoLower.endsWith("@tienda.com")) {
        exito = controlador.getCtrlUsuarios().registrarAdmin(nombre, correo, pwd, pwdConfirm);

        // limpiar contraseñas en memoria
        java.util.Arrays.fill(pwd, '\0');
        java.util.Arrays.fill(pwdConfirm, '\0');

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Administrador registrado correctamente.");
            txtUsuario.setText("");
            txtCorreo.setText("");
            txtContra.setText("");
            txtConfirmar.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar el administrador. Revisa los datos.");
        }
        return;
    }

    //CASO 2: NO es @tienda.com -> mensaje y registrar como CLIENTE
    javax.swing.JOptionPane.showMessageDialog(this,
            "El correo ingresado no pertenece al dominio @tienda.com.\n"
          + "No se puede registrar como administrador.\n"
          + "Se registrará como cliente en el sistema.");

    exito = controlador.getCtrlUsuarios().registrarUsuarios(nombre, correo, pwd, pwdConfirm);

    // limpiar contraseñas en memoria
    java.util.Arrays.fill(pwd, '\0');
    java.util.Arrays.fill(pwdConfirm, '\0');

    if (exito) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente registrado correctamente.");
        txtUsuario.setText("");
        txtCorreo.setText("");
        txtContra.setText("");
        txtConfirmar.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar el cliente. Revisa los datos.");
    }

    }//GEN-LAST:event_btnRegistrarse1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnOfertas;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnRegistrarse1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JToolBar tlbOpciones;
    private javax.swing.JToolBar tlbProducto;
    private javax.swing.JTextField txtBarraBusqueda;
    private javax.swing.JTextField txtConfirmar;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
