

/**
 *
 * @author barre
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public MenuInicio() {
        initComponents();
        setResizable(false);
    }
    
    public void limpiar(){

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPantalla = new javax.swing.JPanel();
        pnlSuperior = new javax.swing.JPanel();
        txtBarraBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLogo = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        tlbOpciones = new javax.swing.JToolBar();
        btnOfertas = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnPerfilTemp = new javax.swing.JButton();
        tlbProducto = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        btnProducto1 = new javax.swing.JButton();
        btnProducto3 = new javax.swing.JButton();
        btnProducto2 = new javax.swing.JButton();
        btnProducto4 = new javax.swing.JButton();
        btnProducto5 = new javax.swing.JButton();
        btnProducto6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(854, 480));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        pnlPantalla.setBackground(new java.awt.Color(255, 255, 255));

        pnlSuperior.setBackground(new java.awt.Color(102, 102, 255));
        pnlSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(1280, 80));

        txtBarraBusqueda.setPreferredSize(new java.awt.Dimension(520, 40));
        txtBarraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarraBusquedaActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLogo.setText("Logo");
        btnLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogo.setMaximumSize(new java.awt.Dimension(256, 80));
        btnLogo.setPreferredSize(new java.awt.Dimension(256, 80));
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });

        btnCarrito.setText("Carrito");
        btnCarrito.setMaximumSize(new java.awt.Dimension(170, 80));
        btnCarrito.setPreferredSize(new java.awt.Dimension(170, 80));
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnPerfil.setText("Perfil");
        btnPerfil.setMaximumSize(new java.awt.Dimension(120, 60));
        btnPerfil.setPreferredSize(new java.awt.Dimension(120, 60));
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(txtBarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtBarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlSuperiorLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tlbOpciones.setBackground(new java.awt.Color(102, 102, 255));
        tlbOpciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tlbOpciones.setRollover(true);
        tlbOpciones.setMaximumSize(new java.awt.Dimension(1280, 60));
        tlbOpciones.setPreferredSize(new java.awt.Dimension(1280, 60));

        btnOfertas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOfertas.setForeground(new java.awt.Color(255, 255, 255));
        btnOfertas.setText("Ofertas");
        btnOfertas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        btnOfertas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOfertas.setMaximumSize(new java.awt.Dimension(160, 60));
        btnOfertas.setPreferredSize(new java.awt.Dimension(85, 60));
        btnOfertas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertasActionPerformed(evt);
            }
        });
        tlbOpciones.add(btnOfertas);

        btnCategorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategorias.setForeground(new java.awt.Color(255, 255, 255));
        btnCategorias.setText("Categorias");
        btnCategorias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        btnCategorias.setFocusable(false);
        btnCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategorias.setMaximumSize(new java.awt.Dimension(160, 60));
        btnCategorias.setPreferredSize(new java.awt.Dimension(85, 60));
        btnCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        tlbOpciones.add(btnCategorias);

        btnPerfilTemp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerfilTemp.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfilTemp.setText("Perfil");
        btnPerfilTemp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        btnPerfilTemp.setFocusable(false);
        btnPerfilTemp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPerfilTemp.setMaximumSize(new java.awt.Dimension(160, 60));
        btnPerfilTemp.setPreferredSize(new java.awt.Dimension(85, 60));
        btnPerfilTemp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPerfilTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilTempActionPerformed(evt);
            }
        });
        tlbOpciones.add(btnPerfilTemp);

        tlbProducto.setBackground(new java.awt.Color(255, 255, 255));
        tlbProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tlbProducto.setRollover(true);
        tlbProducto.setMaximumSize(new java.awt.Dimension(1280, 60));
        tlbProducto.setMinimumSize(new java.awt.Dimension(1280, 60));
        tlbProducto.setPreferredSize(new java.awt.Dimension(1280, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos Destacados");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 60));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 60));
        tlbProducto.add(jLabel1);

        btnProducto1.setText("Producto1");
        btnProducto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProducto1.setMaximumSize(new java.awt.Dimension(296, 202));
        btnProducto1.setPreferredSize(new java.awt.Dimension(296, 202));
        btnProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto1ActionPerformed(evt);
            }
        });

        btnProducto3.setText("Producto3");
        btnProducto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProducto3.setMaximumSize(new java.awt.Dimension(296, 202));
        btnProducto3.setPreferredSize(new java.awt.Dimension(296, 202));
        btnProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto3ActionPerformed(evt);
            }
        });

        btnProducto2.setText("Producto2");
        btnProducto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProducto2.setMaximumSize(new java.awt.Dimension(296, 202));
        btnProducto2.setPreferredSize(new java.awt.Dimension(296, 202));
        btnProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto2ActionPerformed(evt);
            }
        });

        btnProducto4.setText("Producto4");
        btnProducto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProducto4.setMaximumSize(new java.awt.Dimension(296, 202));
        btnProducto4.setPreferredSize(new java.awt.Dimension(296, 202));
        btnProducto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto4ActionPerformed(evt);
            }
        });

        btnProducto5.setText("Producto5");
        btnProducto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProducto5.setMaximumSize(new java.awt.Dimension(296, 202));
        btnProducto5.setPreferredSize(new java.awt.Dimension(296, 202));
        btnProducto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto5ActionPerformed(evt);
            }
        });

        btnProducto6.setText("Producto6");
        btnProducto6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnProducto6.setMaximumSize(new java.awt.Dimension(296, 202));
        btnProducto6.setPreferredSize(new java.awt.Dimension(296, 202));
        btnProducto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tlbOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tlbProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPantallaLayout.createSequentialGroup()
                        .addComponent(btnProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPantallaLayout.createSequentialGroup()
                        .addComponent(btnProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(212, 212, 212))
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(tlbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(tlbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProducto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 82, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPantalla, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBarraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarraBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarraBusquedaActionPerformed

    private void btnOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOfertasActionPerformed

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducto1ActionPerformed

    private void btnProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducto2ActionPerformed

    private void btnProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducto3ActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnPerfilTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilTempActionPerformed

    private void btnProducto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducto4ActionPerformed

    private void btnProducto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducto5ActionPerformed

    private void btnProducto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProducto6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnOfertas;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnPerfilTemp;
    private javax.swing.JButton btnProducto1;
    private javax.swing.JButton btnProducto2;
    private javax.swing.JButton btnProducto3;
    private javax.swing.JButton btnProducto4;
    private javax.swing.JButton btnProducto5;
    private javax.swing.JButton btnProducto6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JToolBar tlbOpciones;
    private javax.swing.JToolBar tlbProducto;
    private javax.swing.JTextField txtBarraBusqueda;
    // End of variables declaration//GEN-END:variables
}
